--DROP TABLE TB_DESPESAS;
--DROP TABLE TB_CATEGORIA;
--DROP TABLE TB_CREDOR;
--DROP TABLE TB_USUARIO;
--DROP SEQUENCE SEQ_DESPESAS;
--DROP SEQUENCE SEQ_CATEGORIA;
--DROP SEQUENCE SEQ_CREDOR;
--DROP SEQUENCE SEQ_USUARIO;

CREATE SEQUENCE SEQ_USUARIO;
CREATE TABLE TB_USUARIO
(
  ID_USUARIO NUMERIC NOT NULL,
  NOME_USUARIO CHARACTER VARYING(256) NOT NULL,
  E_MAIL CHARACTER VARYING(256),  
  USERNAME CHARACTER VARYING(256) NOT NULL,
  SENHA CHARACTER VARYING(256) NOT NULL
);

ALTER TABLE TB_USUARIO ADD CONSTRAINT PK_ID_USUARIO PRIMARY KEY(ID_USUARIO);
ALTER TABLE TB_USUARIO ADD CONSTRAINT UK_EMAIL UNIQUE (E_MAIL);
ALTER TABLE TB_USUARIO ADD CONSTRAINT UK_USERNAME UNIQUE (USERNAME);

CREATE SEQUENCE SEQ_CATEGORIA;
CREATE TABLE TB_CATEGORIA
(
  ID_CATEGORIA NUMERIC NOT NULL,
  DESCRICAO CHARACTER VARYING(256) NOT NULL,
  ID_USUARIO NUMERIC
);

ALTER TABLE TB_CATEGORIA ADD CONSTRAINT PK_ID_CATEGORIA PRIMARY KEY(ID_CATEGORIA);
ALTER TABLE TB_CATEGORIA ADD CONSTRAINT UK_DESCRICAO_CATEGORIA UNIQUE (DESCRICAO);
ALTER TABLE TB_CATEGORIA ADD CONSTRAINT FK_CATEGORIA_ID_USUARIO FOREIGN KEY(ID_USUARIO) REFERENCES TB_USUARIO(ID_USUARIO);

CREATE SEQUENCE SEQ_CREDOR;
CREATE TABLE TB_CREDOR
(
  ID_CREDOR NUMERIC NOT NULL,
  NOME_FANTASIA CHARACTER VARYING(255) NOT NULL,
  ENDERECO CHARACTER VARYING(2000),
  ID_USUARIO NUMERIC
);

ALTER TABLE TB_CREDOR ADD CONSTRAINT PK_ID_CREDOR PRIMARY KEY(ID_CREDOR);
ALTER TABLE TB_CREDOR ADD CONSTRAINT UK_NOME_FANTASIA_CREDOR UNIQUE(NOME_FANTASIA);
ALTER TABLE TB_CREDOR ADD CONSTRAINT FK_CREDOR_ID_USUARIO FOREIGN KEY(ID_USUARIO) REFERENCES TB_USUARIO(ID_USUARIO);


CREATE SEQUENCE SEQ_DESPESAS;
CREATE TABLE TB_DESPESAS
(
  ID_DESPESA NUMERIC NOT NULL,
  ID_CATEGORIA NUMERIC NOT NULL,
  ID_CREDOR NUMERIC,
  VLR_DESPESA NUMERIC(12,2) NOT NULL,
  DT_DESPESA DATE NOT NULL,
  DT_VENCIMENTO DATE,
  ESTADO_DESPESA CHARACTER VARYING(256) DEFAULT 'EM_ABERTO',
  DT_PAGAMENTO DATE,
  VLR_PAGO NUMERIC (12,2),
  FLAG_PARCELADO CHARACTER VARYING(3) ,
  FLAG_MENSAL CHARACTER VARYING(3) ,
  NUM_PARCELAS NUMERIC, 
  ID_USUARIO NUMERIC NOT NULL
);

ALTER TABLE TB_DESPESAS ADD CONSTRAINT PK_ID_DESPESA PRIMARY KEY(ID_DESPESA);
ALTER TABLE TB_DESPESAS ADD CONSTRAINT FK_DESPESAS_ID_CREDOR FOREIGN KEY(ID_CREDOR) REFERENCES TB_CREDOR(ID_CREDOR);
ALTER TABLE TB_DESPESAS ADD CONSTRAINT FK_DESPESAS_ID_CATEGORIA FOREIGN KEY(ID_CATEGORIA) REFERENCES TB_CATEGORIA(ID_CATEGORIA);
ALTER TABLE TB_DESPESAS ADD CONSTRAINT FK_DESPESAS_ID_USUARIO FOREIGN KEY(ID_USUARIO) REFERENCES TB_USUARIO(ID_USUARIO);


﻿create table tb_grupo_usuario (
  id_grupo_usuario numeric NOT NULL,
  nome_grupo varchar(256) NOT NULL,
  CONSTRAINT pk_id_grupo_usuario PRIMARY KEY(id_grupo_usuario)
);


create table tb_rel_grupos_usuarios (
  id_grupos_usuarios numeric NOT NULL,
  id_grupo_usuario numeric NOT NULL, 
  id_usuario numeric NOT NULL,
  usuario_apelido varchar(256),
  CONSTRAINT pk_id_grupos_usuarios PRIMARY KEY(id_grupos_usuarios),
  CONSTRAINT uk_id_grupo_id_usuario UNIQUE(id_grupo_usuario, id_usuario),
  CONSTRAINT fk_usuario FOREIGN KEY (id_usuario)
    REFERENCES tb_usuario(id_usuario),
  CONSTRAINT fk_grupo_usuario FOREIGN KEY(id_grupo_usuario)
    REFERENCES tb_grupo_usuario(id_grupo_usuario)
);

CREATE SEQUENCE seq_grupo_usuario;

CREATE SEQUENCE seq_rel_grupos_usuarios;

INSERT INTO TB_CATEGORIA VALUES (NEXTVAL('SEQ_CATEGORIA'), 'MORADIA');
INSERT INTO TB_CATEGORIA VALUES (NEXTVAL('SEQ_CATEGORIA'), 'ALIMENTAÇÃO');
INSERT INTO TB_CATEGORIA VALUES (NEXTVAL('SEQ_CATEGORIA'), 'TRANSPORTE');
INSERT INTO TB_CATEGORIA VALUES (NEXTVAL('SEQ_CATEGORIA'), 'SAÚDE');
INSERT INTO TB_CATEGORIA VALUES (NEXTVAL('SEQ_CATEGORIA'), 'EDUCAÇÃO');
INSERT INTO TB_CATEGORIA VALUES (NEXTVAL('SEQ_CATEGORIA'), 'LAZER');
INSERT INTO TB_CATEGORIA VALUES (NEXTVAL('SEQ_CATEGORIA'), 'VESTUÁRIO E CUIDADOS PESSOAIS');
INSERT INTO TB_CATEGORIA VALUES (NEXTVAL('SEQ_CATEGORIA'), 'ANIMAIS');
COMMIT;
